CREATE DATABASE PORMADE;

USE PORMADE;

CREATE TABLE COLABORADORES(

    ID INT(20) PRIMARY KEY NOT NULL,
    NOME VARCHAR(20),
    SOBRENOME VARCHAR(20),
    CPF VARCHAR(11),
    RG VARCHAR(13),
    ENDERECO VARCHAR(30),
    NUMERO_CASA INT,
    BAIRRO VARCHAR(20),
    NASCIMENTO DATE

    );

CREATE TABLE SETOR(

    ID_SETOR(20) INT PRIMARY KEY 
)    

INSERT INTO COLABORADORES(

    ID,NOME,SOBRENOME,CPF,RG,ENDERECO,
    NUMERO_CASA,BAIRRO,NASCIMENTO)

    VALUES(
        
    '1','GABRIEL','MULLER','08914412989','132192014',
    'RUA CARLOS CAVALCANTE','1045','SAO BERNARDO','01/08/2002'
    
    );
